//! The app: project rail, top bar, sidebar with the file tree, tabs with editors, status bar.
use std::{
    collections::{HashMap, HashSet},
    path::{Path, PathBuf},
    time::{Duration, Instant},
};

use gyeol::{div, text, uniform_list, Color, Cx, Element, Event, NamedKey, SystemTheme, View};
use madi_git::{diff::{self, FileDiff}, worktree::WorktreeInfo};
use madi_project::{
    config::{Appearance, Config},
    scan::{scan_repo, Issue, ScanOutcome},
    tree::{build_tree_rows, TreeRow},
};

use crate::{
    editor::{self, Editor},
    icons,
    settings::SettingsTab,
    theme::Palette,
};

type El = Element<Madi>;

const ROW_H: f32 = 24.;
const BLINK: Duration = Duration::from_millis(530);
/// Files bigger than this aren't opened (the editor isn't built for huge buffers yet).
const MAX_OPEN_BYTES: u64 = 2 * 1024 * 1024;

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum SidebarView {
    Files,
    Worktrees,
}

/// Which part of the window has the keyboard.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Focus {
    Tree,
    Editor,
}

pub struct Tab {
    pub path: PathBuf,
    pub title: String,
    /// A preview tab (italic) is replaced by the next thing opened in preview; editing it, or opening
    /// it again for real, makes it a regular tab.
    pub preview: bool,
    pub editor: Editor,
}

/// A diff is a tab just like an editor, but its rows are generated by git rather than editable.
pub struct DiffTab {
    pub title: String,
    pub file: FileDiff,
}

/// What is remembered per project so switching projects never loses your place.
#[derive(Default)]
pub struct Workspace {
    pub expanded: HashSet<PathBuf>,
    pub selected: Option<PathBuf>,
    pub tabs: Vec<Tab>,
    pub active: Option<usize>,
    pub diff: Option<DiffTab>,
    pub showing_diff: bool,
}

pub struct Madi {
    pub config: Config,
    pub repo: String,
    pub workspaces: HashMap<String, Workspace>,
    pub tree_rows: Vec<TreeRow>,
    pub sidebar_view: SidebarView,
    pub sidebar_width: f32,
    pub worktrees: Vec<WorktreeInfo>,
    pub pins: HashMap<String, String>,
    pub changes: Vec<FileDiff>,
    pub selected_worktree: Option<usize>,
    pub selected_change: Option<usize>,
    pub worktree_issue: Option<Issue>,
    /// Hides everything but the top bar and the editor area.
    pub focus_mode: bool,
    pub focus: Focus,
    pub settings_open: bool,
    pub settings_tab: SettingsTab,
    /// The dirty editor tab awaiting a Save / Discard / Cancel decision.
    pub close_confirm: Option<usize>,
    /// The last failure to show in the top bar (a file that can't be opened or saved).
    pub error: Option<String>,
    pub blink_epoch: Instant,
    pub window_focused: bool,
}

impl Madi {
    pub fn new(initial: Option<String>, config: Config) -> Madi {
        let mut app = Madi {
            config,
            repo: String::new(),
            workspaces: HashMap::new(),
            tree_rows: Vec::new(),
            sidebar_view: SidebarView::Files,
            sidebar_width: 280.,
            worktrees: Vec::new(),
            pins: HashMap::new(),
            changes: Vec::new(),
            selected_worktree: None,
            selected_change: None,
            worktree_issue: None,
            focus_mode: false,
            focus: Focus::Tree,
            settings_open: false,
            settings_tab: SettingsTab::General,
            close_confirm: None,
            error: None,
            blink_epoch: Instant::now(),
            window_focused: true,
        };
        match initial {
            // A file: open its folder as the project and the file in a tab.
            Some(path) if Path::new(&path).is_file() => {
                let file = PathBuf::from(&path);
                if let Some(dir) = file.parent() {
                    app.open_project(dir.to_string_lossy().into_owned());
                    app.open_file(file, false);
                }
            }
            initial => {
                if let Some(path) = initial.or_else(|| app.config.last_project.clone()) {
                    app.open_project(path);
                }
            }
        }
        app
    }

    pub fn project_name(path: &str) -> String {
        path.rsplit(['/', '\\']).find(|s| !s.is_empty()).unwrap_or(path).to_string()
    }

    /// Opens (and remembers) a project folder.
    pub fn open_project(&mut self, path: String) {
        if !self.config.projects.contains(&path) {
            self.config.projects.push(path.clone());
        }
        self.config.last_project = Some(path.clone());
        self.config.save();
        self.repo = path;
        self.error = None;
        self.refresh_tree();
        self.refresh_worktrees();
    }

    fn workspace(&self) -> Option<&Workspace> {
        self.workspaces.get(&self.repo)
    }

    fn workspace_mut(&mut self) -> &mut Workspace {
        self.workspaces.entry(self.repo.clone()).or_default()
    }

    pub fn refresh_tree(&mut self) {
        let expanded = self.workspace().map(|w| w.expanded.clone()).unwrap_or_default();
        self.tree_rows = if self.repo.is_empty() { Vec::new() } else { build_tree_rows(Path::new(&self.repo), &expanded) };
    }

    pub fn toggle_dir(&mut self, path: &Path) {
        let ws = self.workspace_mut();
        if !ws.expanded.remove(path) {
            ws.expanded.insert(path.to_path_buf());
        }
        self.refresh_tree();
    }

    pub fn select(&mut self, path: PathBuf) {
        self.workspace_mut().selected = Some(path);
    }

    // ---- tabs --------------------------------------------------------------------------------

    pub fn active_tab(&self) -> Option<&Tab> {
        let ws = self.workspace()?;
        ws.tabs.get(ws.active?)
    }

    pub fn active_editor(&self) -> Option<&Editor> {
        if self.workspace()?.showing_diff { None } else { self.active_tab().map(|tab| &tab.editor) }
    }

    pub fn active_editor_mut(&mut self) -> Option<&mut Editor> {
        let ws = self.workspaces.get_mut(&self.repo)?;
        let ix = ws.active?;
        if ws.showing_diff { None } else { ws.tabs.get_mut(ix).map(|tab| &mut tab.editor) }
    }

    /// Opens a file as a tab (or focuses its tab). A preview open replaces the current preview tab; a
    /// regular open pins whatever it lands on.
    pub fn open_file(&mut self, path: PathBuf, preview: bool) {
        let name = path.file_name().map(|n| n.to_string_lossy().into_owned()).unwrap_or_default();
        self.focus = Focus::Editor;
        self.blink_epoch = Instant::now();
        if let Some(ix) = self.workspace().and_then(|w| w.tabs.iter().position(|t| t.path == path)) {
            let ws = self.workspace_mut();
            if !preview {
                ws.tabs[ix].preview = false;
            }
            ws.active = Some(ix);
            ws.showing_diff = false;
            return;
        }
        let opened = std::fs::metadata(&path)
            .map_err(|e| e.to_string())
            .and_then(|m| if m.len() > MAX_OPEN_BYTES { Err("file is too large to open".to_string()) } else { Ok(()) })
            .and_then(|_| std::fs::read(&path).map_err(|e| e.to_string()))
            .and_then(|bytes| String::from_utf8(bytes).map_err(|_| "not a UTF-8 text file".to_string()));
        let text = match opened {
            Ok(text) => text,
            Err(reason) => {
                self.error = Some(format!("Can't open {name}: {reason}"));
                return;
            }
        };
        self.error = None;
        let tab = Tab { path: path.clone(), title: name, preview, editor: Editor::new(&text, path) };
        let ws = self.workspace_mut();
        ws.showing_diff = false;
        let ix = match (preview, ws.tabs.iter().position(|t| t.preview)) {
            (true, Some(replace)) => {
                ws.tabs[replace] = tab;
                replace
            }
            _ => {
                ws.tabs.push(tab);
                ws.tabs.len() - 1
            }
        };
        ws.active = Some(ix);
    }

    pub fn activate_tab(&mut self, ix: usize) {
        let ws = self.workspace_mut();
        if ix < ws.tabs.len() {
            ws.active = Some(ix);
            ws.showing_diff = false;
            self.focus = Focus::Editor;
            self.blink_epoch = Instant::now();
        }
    }

    /// Closes a tab. A file with unsaved changes stays open until it is saved (no confirmation dialog yet).
    pub fn close_tab(&mut self, ix: usize) {
        let Some(tab) = self.workspace().and_then(|w| w.tabs.get(ix)) else { return };
        if tab.editor.doc.is_dirty() {
            self.close_confirm = Some(ix);
            return;
        }
        self.remove_tab(ix);
    }

    fn remove_tab(&mut self, ix: usize) {
        let ws = self.workspace_mut();
        ws.tabs.remove(ix);
        ws.active = match ws.active {
            _ if ws.tabs.is_empty() => None,
            Some(a) if a > ix => Some(a - 1),
            Some(a) if a == ix => Some(ix.min(ws.tabs.len() - 1)),
            other => other,
        };
    }

    fn resolve_close(&mut self, save: bool, cx: &mut Cx) {
        let Some(ix) = self.close_confirm.take() else { return };
        if save {
            let Some(tab) = self.workspace_mut().tabs.get_mut(ix) else { return };
            let name = tab.title.clone();
            match std::fs::write(&tab.path, tab.editor.doc.text_for_save()) {
                Ok(()) => tab.editor.doc.mark_saved(),
                Err(e) => { self.error = Some(format!("Can't save {name}: {e}")); return; }
            }
        }
        self.remove_tab(ix);
        self.touched(cx);
    }

    // ---- worktrees and diffs -----------------------------------------------------------------

    fn refresh_worktrees(&mut self) {
        self.worktrees.clear();
        self.changes.clear();
        self.selected_worktree = None;
        self.selected_change = None;
        self.worktree_issue = None;
        if self.repo.is_empty() {
            return;
        }
        let saved = self.config.pins.get(&self.repo).cloned().unwrap_or_default();
        match scan_repo(self.repo.clone(), saved) {
            Ok(ScanOutcome::Loaded(scan)) => {
                self.worktrees = scan.worktrees;
                self.pins = scan.pins;
                self.config.pins.insert(self.repo.clone(), self.pins.clone());
                self.config.save();
            }
            Ok(ScanOutcome::Issue(issue)) => self.worktree_issue = Some(issue),
            Err(reason) => self.error = Some(format!("Can't scan git repository: {reason}")),
        }
    }

    fn select_worktree(&mut self, ix: usize) {
        let Some(worktree) = self.worktrees.get(ix) else { return };
        self.selected_worktree = Some(ix);
        self.selected_change = None;
        self.changes.clear();
        self.error = None;
        let base = self.pins.get(&worktree.path).cloned().unwrap_or_default();
        match diff::diff_against_base(worktree.path.clone(), base) {
            Ok(result) => self.changes = result.files,
            Err(reason) => self.error = Some(format!("Can't load changes: {reason}")),
        }
    }

    fn open_diff(&mut self, ix: usize) {
        let Some(file) = self.changes.get(ix) else { return };
        self.selected_change = Some(ix);
        let diff = DiffTab { title: file.path.clone(), file: FileDiff {
            path: file.path.clone(), status: file.status.clone(), additions: file.additions, deletions: file.deletions,
            section: file.section, binary: file.binary, lines: file.lines.iter().map(|line| madi_git::diff::DiffLine {
                tag: line.tag, old_lineno: line.old_lineno, new_lineno: line.new_lineno,
                segments: line.segments.iter().map(|segment| madi_git::diff::Segment { text: segment.text.clone(), emphasized: segment.emphasized }).collect(),
                skipped: line.skipped,
            }).collect(),
        } };
        let ws = self.workspace_mut();
        ws.diff = Some(diff);
        ws.showing_diff = true;
        self.focus = Focus::Editor;
    }

    fn close_diff(&mut self) {
        let ws = self.workspace_mut();
        ws.diff = None;
        ws.showing_diff = false;
    }

    fn resolve_dark(&self, cx: &Cx) -> bool {
        match self.config.appearance {
            Appearance::Light => false,
            Appearance::Dark => true,
            Appearance::System => cx.system_theme() == SystemTheme::Dark,
        }
    }

    /// The window heading: what is open (bold) and where it lives (dim).
    pub fn title_parts(&self) -> (String, String) {
        let project = Self::project_name(&self.repo);
        if let Some(diff) = self.workspace().filter(|ws| ws.showing_diff).and_then(|ws| ws.diff.as_ref()) {
            return (diff.title.clone(), format!("{project} · diff"));
        }
        match self.active_tab() {
            Some(tab) => {
                let dir = tab.path.strip_prefix(&self.repo).ok().and_then(|p| p.parent()).map(|d| d.display().to_string()).unwrap_or_default();
                (tab.title.clone(), if dir.is_empty() { project } else { format!("{project} · {dir}") })
            }
            None if self.repo.is_empty() => ("Madi".into(), String::new()),
            None => (project, String::new()),
        }
    }

    // ---- views -------------------------------------------------------------------------------

    fn rail(&self, p: &Palette) -> El {
        let tiles = self.config.projects.iter().map(|path| {
            let active = *path == self.repo;
            let letter = Self::project_name(path).chars().next().map(|c| c.to_uppercase().to_string()).unwrap_or_default();
            let target = path.clone();
            let tile = div()
                .size(32.)
                .items_center()
                .justify_center()
                .rounded(6.)
                .on_click(move |s: &mut Madi, _| s.open_project(target.clone()))
                .child(text(letter).text_color(if active { p.bg } else { p.text_dim }));
            if active { tile.bg(p.text_strong) } else { tile.border(1., p.border).hover_bg(p.selected) }
        });
        div().w(48.).bg(p.chrome).items_center().py(8.).gap(8.).children(tiles)
    }

    fn icon_button(&self, p: &Palette, active: bool, icon: El, on_click: impl Fn(&mut Madi, &mut Cx) + 'static) -> El {
        div()
            .size(28.)
            .items_center()
            .justify_center()
            .rounded(6.)
            .bg(if active { p.selected } else { Color::TRANSPARENT })
            .hover_bg(p.selected)
            .on_click(on_click)
            .child(icon)
    }

    fn close_confirm_modal(&self, p: &Palette) -> Option<El> {
        let ix = self.close_confirm?;
        let title = self.workspace()?.tabs.get(ix)?.title.clone();
        let button = |label: &'static str, color: Color, action: fn(&mut Madi, &mut Cx)| {
            div().px(10.).py(6.).rounded(6.).bg(color).hover_bg(p.selected).on_click(action).child(text(label).text_size(12.).text_color(p.text_strong))
        };
        Some(div().inset(0.).items_center().justify_center().bg(Color::hex(0).with_alpha(0.35)).on_click(|s: &mut Madi, _| s.close_confirm = None).child(
            div().w(380.).p(20.).gap(14.).rounded(8.).border(1., p.border).bg(p.bg).on_click(|_: &mut Madi, _| {})
                .child(text("Unsaved changes").text_size(15.).text_color(p.text_strong))
                .child(text(format!("Save changes to \"{title}\" before closing? ")).text_size(12.).text_color(p.text_dim))
                .child(div().row().justify_end().gap(8.)
                    .child(button("Cancel", p.panel, |s, _| s.close_confirm = None))
                    .child(button("Discard", p.red.with_alpha(0.35), |s, cx| s.resolve_close(false, cx)))
                    .child(button("Save", p.selected, |s, cx| s.resolve_close(true, cx)))),
        ))
    }

    fn topbar(&self, p: &Palette) -> El {
        let (name, place) = self.title_parts();
        let mut bar = div()
            .row()
            .items_center()
            .h(40.)
            .px(16.)
            .gap(12.)
            .bg(p.chrome)
            .child(text(name).text_color(p.text_strong))
            .child(text(place).text_size(12.).text_color(p.text_dim));
        if let Some(error) = &self.error {
            bar = bar.child(text(error.clone()).text_size(12.).text_color(p.red));
        }
        let bar = bar
            .child(div().grow())
            .child(self.icon_button(p, self.focus_mode, icons::focus(if self.focus_mode { p.text_strong } else { p.text_dim }), |s, _| {
                s.focus_mode = !s.focus_mode
            }))
            .child(self.icon_button(p, self.settings_open, icons::sliders(if self.settings_open { p.text_strong } else { p.text_dim }), |s, _| {
                if s.settings_open {
                    s.close_settings();
                } else {
                    s.open_settings();
                }
            }));
        div().col().child(bar).child(div().h(1.).bg(p.border))
    }

    fn tree_row(&self, i: usize, p: &Palette) -> El {
        let row = &self.tree_rows[i];
        let selected = self.workspace().and_then(|w| w.selected.as_ref()) == Some(&row.path);
        let (path, is_dir) = (row.path.clone(), row.is_dir);
        let arrow = if !row.is_dir { "" } else if row.expanded { "▾" } else { "▸" };
        div()
            .row()
            .items_center()
            .px(8.)
            .bg(if selected { p.selected } else { Color::TRANSPARENT })
            .hover_bg(p.selected)
            .cursor(gyeol::Cursor::Pointer)
            // A press does the work, so a double click can pin the file's preview tab.
            .on_mouse_down(move |s: &mut Madi, _, e| {
                s.focus = Focus::Tree;
                s.select(path.clone());
                if is_dir {
                    s.toggle_dir(&path);
                } else {
                    s.open_file(path.clone(), e.click_count < 2);
                }
            })
            .child(div().w(row.depth as f32 * 14.))
            .child(div().w(14.).child(text(arrow).text_size(10.).text_color(p.text_dim)))
            .child(text(row.name.clone()).text_size(12.).text_color(if row.is_dir { p.text_strong } else { p.text }))
    }

    fn worktrees_view(&self, cx: &Cx, p: &Palette) -> El {
        if let Some(issue) = self.worktree_issue {
            return div().grow().items_center().justify_center().child(text(issue.label()).text_size(12.).text_color(p.text_dim));
        }
        if self.worktrees.is_empty() {
            return div().grow().items_center().justify_center().child(text("No worktrees").text_size(12.).text_color(p.text_dim));
        }
        let worktrees = uniform_list(cx, ("worktrees", &self.repo), self.worktrees.len(), 62., |i| {
            let wt = &self.worktrees[i];
            let selected = self.selected_worktree == Some(i);
            let branch = wt.branch.clone().unwrap_or_else(|| "(detached)".into());
            let status = match (wt.ahead, wt.behind) { (Some(0), Some(0)) => "up to date".into(), (Some(a), Some(b)) => format!("↑{a} ↓{b}"), _ => String::new() };
            div().px(8.).py(6.).rounded(6.)
                .bg(if selected { p.selected } else { Color::TRANSPARENT }).hover_bg(p.selected)
                .on_click(move |s: &mut Madi, _| s.select_worktree(i))
                .child(text(wt.name.clone()).text_size(12.).text_color(p.text_strong))
                .child(text(format!("{branch}  {status}")).text_size(11.).text_color(p.text_dim))
        }).h(220.).p(8.).scrollbar(p.text_dim.with_alpha(0.4));
        let changes_title = self.selected_worktree.and_then(|i| self.worktrees.get(i)).map(|wt| format!("CHANGES · vs {}", self.pins.get(&wt.path).cloned().unwrap_or_default())).unwrap_or_else(|| "CHANGES".into());
        let changes = if self.selected_worktree.is_none() {
            div().grow().p(16.).child(text("Select a worktree to see its changes").text_size(12.).text_color(p.text_dim))
        } else if self.changes.is_empty() {
            div().grow().p(16.).child(text("No changes").text_size(12.).text_color(p.text_dim))
        } else {
            uniform_list(cx, ("worktree-changes", &self.repo), self.changes.len(), ROW_H, |i| {
                let file = &self.changes[i];
                let selected = self.selected_change == Some(i);
                let counts = format!("+{}  −{}", file.additions, file.deletions);
                div().row().items_center().px(8.).rounded(4.)
                    .bg(if selected { p.selected } else { Color::TRANSPARENT }).hover_bg(p.selected)
                    .on_click(move |s: &mut Madi, _| s.open_diff(i))
                    .child(text(file.path.clone()).text_size(12.).text_color(p.text).grow())
                    .child(text(counts).text_size(11.).text_color(p.text_dim))
            }).grow().p(8.).scrollbar(p.text_dim.with_alpha(0.4))
        };
        div().grow().child(worktrees).child(div().h(1.).bg(p.border_soft)).child(div().px(12.).py(8.).child(text(changes_title).text_size(11.).text_color(p.text_dim))).child(div().h(1.).bg(p.border_soft)).child(changes)
    }

    fn sidebar(&self, cx: &Cx, p: &Palette) -> El {
        let seg = |label: &str, view: SidebarView| {
            let active = self.sidebar_view == view;
            div()
                .px(8.)
                .py(4.)
                .rounded(6.)
                .bg(if active { p.selected } else { Color::TRANSPARENT })
                .on_click(move |s: &mut Madi, _| s.sidebar_view = view)
                .child(text(label).text_size(12.).text_color(if active { p.text_strong } else { p.text_dim }))
        };
        let body = match self.sidebar_view {
            SidebarView::Files => uniform_list(cx, ("tree", &self.repo), self.tree_rows.len(), ROW_H, |i| self.tree_row(i, p))
                .grow()
                .p(8.)
                .scrollbar(p.text_dim.with_alpha(0.4)),
            SidebarView::Worktrees => self.worktrees_view(cx, p),
        };
        div()
            .row()
            .w(self.sidebar_width)
            .child(
                div()
                    .grow()
                    .bg(p.panel)
                    .child(
                        div()
                            .px(12.)
                            .pt(12.)
                            .pb(8.)
                            .gap(8.)
                            .child(div().px(4.).child(text(Self::project_name(&self.repo)).text_color(p.text_strong)))
                            .child(div().row().gap(4.).child(seg("Files", SidebarView::Files)).child(seg("Worktrees", SidebarView::Worktrees))),
                    )
                    .child(div().h(1.).bg(p.border_soft))
                    .child(body),
            )
            .child(div().w(1.).bg(p.border))
    }

    fn tab_bar(&self, p: &Palette) -> El {
        let ws = self.workspace();
        let active = ws.and_then(|w| w.active);
        let mut tabs: Vec<El> = ws.into_iter().flat_map(|w| w.tabs.iter().enumerate()).map(|(i, tab)| {
            let dirty = tab.editor.doc.is_dirty();
            let is_active = active == Some(i);
            let title = text(tab.title.clone()).text_size(12.).text_color(if is_active { p.text_strong } else { p.text_dim });
            let close = div()
                .w(14.)
                .items_center()
                .rounded(4.)
                .hover_bg(p.border)
                .on_click(move |s: &mut Madi, _| s.close_tab(i))
                .child(text(if dirty { "●" } else { "×" }).text_size(12.).text_color(if dirty { p.amber } else { p.text_dim }));
            div()
                .row()
                .items_center()
                .h(34.)
                .px(12.)
                .gap(8.)
                .bg(if is_active { p.bg } else { Color::TRANSPARENT })
                .hover_bg(if is_active { p.bg } else { p.selected })
                .on_click(move |s: &mut Madi, _| s.activate_tab(i))
                .child(if tab.preview { title.text_italic() } else { title })
                .child(close)
                .child(div().w(1.).bg(p.border))
        }).collect();
        if let Some(diff) = ws.and_then(|w| w.diff.as_ref()) {
            let is_active = ws.is_some_and(|w| w.showing_diff);
            let title = diff.title.clone();
            tabs.push(
                div().row().items_center().h(34.).px(12.).gap(8.)
                    .bg(if is_active { p.bg } else { Color::TRANSPARENT }).hover_bg(p.selected)
                    .on_click(|s: &mut Madi, _| { s.workspace_mut().showing_diff = true; s.focus = Focus::Editor; })
                    .child(text(title).text_size(12.).text_color(if is_active { p.text_strong } else { p.text_dim }))
                    .child(div().w(14.).items_center().rounded(4.).hover_bg(p.border).on_click(|s: &mut Madi, _| s.close_diff()).child(text("×").text_size(12.).text_color(p.text_dim)))
                    .child(div().w(1.).bg(p.border)),
            );
        }
        div().col().child(div().row().h(34.).bg(p.chrome).children(tabs)).child(div().h(1.).bg(p.border))
    }

    fn diff_view(&self, cx: &Cx, p: &Palette) -> El {
        let Some(diff) = self.workspace().and_then(|ws| ws.diff.as_ref()) else { return div().grow() };
        if diff.file.binary {
            return div().grow().items_center().justify_center().child(text("Binary file — diff is unavailable").text_size(12.).text_color(p.text_dim));
        }
        let widest = diff.file.lines.iter().flat_map(|line| line.segments.iter()).map(|segment| segment.text.chars().count()).sum::<usize>().max(80);
        let min_width = 100. + widest as f32 * self.config.font_size() * 0.62;
        let path = diff.file.path.clone();
        let rows = uniform_list(cx, ("diff-lines", &self.repo, &path), diff.file.lines.len(), 20., |i| {
            let line = &diff.file.lines[i];
            if line.tag == "gap" {
                return div().min_w(min_width).items_center().justify_center().bg(p.panel).child(text("⋯ unchanged ⋯").text_size(11.).text_color(p.text_dim));
            }
            let (bg, fg, marker) = match line.tag { "insert" => (p.add_bg, p.add_fg, "+"), "delete" => (p.del_bg, p.del_fg, "-"), _ => (Color::TRANSPARENT, p.text, " ") };
            let old = line.old_lineno.map(|n| n.to_string()).unwrap_or_default();
            let new = line.new_lineno.map(|n| n.to_string()).unwrap_or_default();
            let source = line.segments.iter().map(|s| s.text.as_str()).collect::<String>();
            div().row().items_center().min_w(min_width).bg(bg)
                .child(div().w(42.).px(6.).justify_end().child(text(old).text_size(11.).text_color(p.text_dim)))
                .child(div().w(42.).px(6.).justify_end().child(text(new).text_size(11.).text_color(p.text_dim)))
                .child(div().w(16.).child(text(marker).text_size(12.).text_color(fg)))
                .child(text(source).text_size(self.config.font_size()).text_family(editor::MONO).text_color(fg))
        }).grow().min_w(min_width).scrollbar(p.text_dim.with_alpha(0.4));
        div().id(("diff-x", &self.repo, &path)).grow().overflow_x_scroll().child(div().w(min_width).h_full().child(rows.w(min_width)))
    }

    fn main_area(&self, cx: &mut Cx, p: &Palette) -> El {
        let content = if self.workspace().is_some_and(|ws| ws.showing_diff) {
            self.diff_view(cx, p)
        } else { match self.active_editor() {
            Some(ed) => {
                let focused = self.focus == Focus::Editor && self.window_focused;
                let blink_on = (self.blink_epoch.elapsed().as_millis() / BLINK.as_millis()) % 2 == 0;
                if focused {
                    cx.request_redraw_after(Duration::from_millis((BLINK.as_millis() - self.blink_epoch.elapsed().as_millis() % BLINK.as_millis()) as u64));
                }
                editor::view(ed, cx, p, self.config.font_size(), focused && blink_on)
            }
            None => div()
                .grow()
                .items_center()
                .justify_center()
                .gap(8.)
                .child(text("Nothing open").text_size(15.).text_color(p.text))
                .child(text("Pick a file in Files to edit it").text_size(12.).text_color(p.text_dim)),
        }};
        div().grow().child(self.tab_bar(p)).child(content)
    }

    fn status_bar(&self, p: &Palette) -> El {
        let details = self.active_editor().map(|e| {
            let (line, col) = e.doc.cursor_display();
            format!("Ln {line}, Col {col}   {}   UTF-8", e.doc.line_ending())
        });
        div().col().child(div().h(1.).bg(p.border)).child(
            div()
                .row()
                .items_center()
                .h(27.)
                .px(12.)
                .bg(p.chrome)
                .child(text(self.repo.clone()).text_size(12.).text_color(p.text_dim))
                .child(div().grow())
                .child(text(details.unwrap_or_default()).text_size(12.).text_color(p.text_dim)),
        )
    }
}

impl View for Madi {
    fn view(&self, cx: &mut Cx) -> El {
        let p = Palette::new(self.resolve_dark(cx));
        let mut middle = div().row().grow();
        if !self.focus_mode {
            middle = middle.child(self.rail(&p)).child(div().w(1.).bg(p.border)).child(self.sidebar(cx, &p));
        }
        let mut root = div().bg(p.bg).text_color(p.text).text_size(13.).child(self.topbar(&p)).child(middle.child(self.main_area(cx, &p)));
        if !self.focus_mode {
            root = root.child(self.status_bar(&p));
        }
        if let Some(settings) = self.settings_modal(&p) {
            root = root.child(settings);
        }
        if let Some(confirm) = self.close_confirm_modal(&p) {
            root = root.child(confirm);
        }
        root
    }

    fn event(&mut self, event: &Event, cx: &mut Cx) {
        match event {
            Event::FocusChanged(focused) => self.window_focused = *focused,
            Event::KeyDown { key, .. } => {
                if self.close_confirm.is_some() {
                    if matches!(key, gyeol::Key::Named(NamedKey::Escape)) { self.close_confirm = None; }
                    return;
                }
                if self.settings_key(key, cx) {
                    return;
                }
                if matches!(key, gyeol::Key::Char(c) if c == ",") && cx.modifiers.command() {
                    self.open_settings();
                    return;
                }
                self.editor_event(event, cx);
            }
            _ if !self.settings_open && self.close_confirm.is_none() => self.editor_event(event, cx),
            _ => {}
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use gyeol::testing::TestHost;
    use crate::editor::Editor;

    /// A project with `src/main.rs`, `src/lib.rs` and `README.md` in a fresh temp folder.
    fn project(name: &str) -> (PathBuf, String) {
        let root = std::env::temp_dir().join(format!("madi-gyeol-test-{name}"));
        let _ = std::fs::remove_dir_all(&root);
        let proj = root.join("proj");
        std::fs::create_dir_all(proj.join("src")).unwrap();
        std::fs::write(proj.join("src/main.rs"), "fn main() {}\n").unwrap();
        std::fs::write(proj.join("src/lib.rs"), "\n").unwrap();
        std::fs::write(proj.join("README.md"), "# hi\n").unwrap();
        let path = proj.to_string_lossy().into_owned();
        (root, path)
    }

    fn app(name: &str) -> (TestHost<Madi>, PathBuf, String) {
        let (root, path) = project(name);
        let config = Config::at(Some(root.join("config.json")));
        (TestHost::new(Madi::new(Some(path.clone()), config), (1200., 800.)), root, path)
    }

    fn has_text(host: &TestHost<Madi>, content: &str) -> bool {
        host.scene().texts().any(|t| t.content == content)
    }

    #[test]
    fn the_sidebar_lists_folders_first_and_folders_expand_on_click() {
        let (mut host, _, _) = app("tree");
        let names: Vec<&str> = host.scene().texts().map(|t| t.content.as_str()).collect();
        let (src, readme) = (names.iter().position(|n| *n == "src").unwrap(), names.iter().position(|n| *n == "README.md").unwrap());
        assert!(src < readme, "folders come first");
        assert!(!has_text(&host, "main.rs"), "collapsed");

        host.click_text("src");
        assert!(has_text(&host, "main.rs") && has_text(&host, "lib.rs"), "expanded");
        host.click_text("src");
        assert!(!has_text(&host, "main.rs"), "collapsed again");
    }

    #[test]
    fn selecting_a_file_updates_the_heading() {
        let (mut host, _, path) = app("select");
        assert_eq!(host.state().title_parts(), (Madi::project_name(&path), String::new()));
        host.click_text("src");
        host.click_text("main.rs");
        assert_eq!(host.state().title_parts(), ("main.rs".to_string(), format!("{} · src", Madi::project_name(&path))));
        assert!(has_text(&host, "main.rs"), "the heading and the tree both show it");
    }

    #[test]
    fn the_rail_switches_between_projects_and_remembers_each_ones_folders() {
        let (root, first) = project("rail-a");
        let (_, second) = project("rail-b");
        let config = Config::at(Some(root.join("config.json")));
        let mut app = Madi::new(Some(first.clone()), config);
        app.open_project(second.clone());
        let mut host = TestHost::new(app, (1200., 800.));
        assert_eq!(host.state().repo, second);

        host.click_text("src");
        assert!(has_text(&host, "main.rs"));
        // Two tiles, both labelled "P" (proj): the first one is at the top of the rail.
        host.click((24., 40. + 8. + 16. + 1.));
        assert_eq!(host.state().repo, first);
        assert!(!has_text(&host, "main.rs"), "the first project's tree was never expanded");
        host.click((24., 40. + 8. + 32. + 8. + 16. + 1.));
        assert_eq!(host.state().repo, second);
        assert!(has_text(&host, "main.rs"), "the second project's expansion was remembered");
    }

    #[test]
    fn focus_mode_hides_the_chrome_around_the_editor() {
        let (mut host, _, path) = app("focus");
        let name = Madi::project_name(&path);
        assert!(has_text(&host, &path), "the status bar shows the project path");
        host.state_mut().focus_mode = true;
        host.frame();
        assert!(!has_text(&host, &path), "no status bar");
        assert!(!has_text(&host, "Files"), "no sidebar");
        assert!(has_text(&host, &name), "the top bar stays");
    }

    #[test]
    fn the_theme_follows_the_system_unless_forced() {
        let (mut host, _, _) = app("theme");
        let light = host.scene().quads().next().unwrap().background;
        host.set_system_theme(SystemTheme::Dark);
        let dark = host.scene().quads().next().unwrap().background;
        assert_ne!(light, dark, "System follows the OS");

        host.state_mut().config.appearance = Appearance::Light;
        host.frame();
        assert_eq!(host.scene().quads().next().unwrap().background, light, "Light ignores a dark OS");
    }

    // ---- the editor ------------------------------------------------------------------------

    use gyeol::{Ime, Key, Modifiers, NamedKey, Shaper};
    use madi_text::Pos;

    fn cmd() -> Modifiers {
        // Both, so the platform's shortcut modifier is held whichever one it is.
        Modifiers { logo: true, ctrl: true, ..Default::default() }
    }

    fn typed(host: &mut TestHost<Madi>, s: &str) {
        for c in s.chars() {
            host.key(Key::Char(c.to_string()), Some(&c.to_string()));
        }
    }

    fn press(host: &mut TestHost<Madi>, key: Key) {
        host.key(key, None);
    }

    fn doc_text(host: &TestHost<Madi>) -> String {
        host.state().active_editor().unwrap().doc.text()
    }

    fn shortcut(host: &mut TestHost<Madi>, letter: &str) {
        host.set_modifiers(cmd());
        host.key(Key::Char(letter.into()), Some(letter));
        host.set_modifiers(Modifiers::default());
    }

    #[test]
    fn opening_a_file_shows_its_lines_in_a_preview_tab_that_double_click_pins() {
        let (mut host, _, _) = app("open");
        host.click_text("README.md");
        assert!(has_text(&host, "# hi"), "the file's first line");
        assert!(has_text(&host, "1"), "line numbers in the gutter");
        let ws = host.state().workspace().unwrap();
        assert_eq!((ws.tabs.len(), ws.tabs[0].preview), (1, true));

        // "README.md" is now also the heading and the tab's title: take the one in the sidebar (left, below the top bar).
        let row = host.scene().texts().find(|t| t.content == "README.md" && t.origin.0 < 330. && t.origin.1 > 100.).expect("the tree row");
        let at = (row.origin.0 + 10., row.origin.1 + 6.);
        host.mouse_down_n(at, 2);
        host.mouse_up(at);
        assert!(!host.state().workspace().unwrap().tabs[0].preview, "a double click keeps the tab");
    }

    #[test]
    fn a_preview_tab_is_replaced_until_it_is_pinned_by_editing() {
        let (mut host, _, _) = app("preview");
        host.click_text("src");
        host.click_text("lib.rs");
        host.click_text("main.rs");
        assert_eq!(host.state().workspace().unwrap().tabs.len(), 1, "the second preview replaced the first");
        typed(&mut host, "x");
        assert!(!host.state().workspace().unwrap().tabs[0].preview, "editing pins it");
        host.click_text("lib.rs");
        assert_eq!(host.state().workspace().unwrap().tabs.len(), 2, "so the next preview gets its own tab");
    }

    #[test]
    fn typing_backspace_and_undo() {
        let (mut host, _, _) = app("typing");
        host.click_text("README.md");
        typed(&mut host, "ab");
        assert_eq!(doc_text(&host), "ab# hi\n");
        press(&mut host, Key::Named(NamedKey::Backspace));
        assert_eq!(doc_text(&host), "a# hi\n");
        shortcut(&mut host, "z");
        assert_eq!(doc_text(&host), "ab# hi\n", "undo brings the deleted character back");
        host.set_modifiers(Modifiers { shift: true, ..cmd() });
        host.key(Key::Char("Z".into()), Some("Z"));
        assert_eq!(doc_text(&host), "a# hi\n", "shift + undo shortcut redoes");
    }

    #[test]
    fn korean_composes_through_the_input_method() {
        let (mut host, _, _) = app("ime");
        host.click_text("README.md");
        for step in ["ㅎ", "하", "한"] {
            host.ime(Ime::Preedit { text: step.into(), cursor: None });
            assert_eq!(doc_text(&host), format!("{step}# hi\n"), "composition replaces the previous provisional text");
            assert!(host.state().active_editor().unwrap().doc.marked().is_some());
        }
        press(&mut host, Key::Named(NamedKey::Backspace));
        assert_eq!(doc_text(&host), "한# hi\n", "keys belong to the input method while composing");

        host.ime(Ime::Commit("한".into()));
        assert_eq!(doc_text(&host), "한# hi\n");
        assert!(host.state().active_editor().unwrap().doc.marked().is_none());
        host.ime(Ime::Preedit { text: "ㄱ".into(), cursor: None });
        host.ime(Ime::Preedit { text: "".into(), cursor: None });
        assert_eq!(doc_text(&host), "한# hi\n", "cancelling a composition leaves nothing behind");
    }

    #[test]
    fn saving_writes_the_file_and_clears_the_unsaved_marker() {
        let (mut host, _, path) = app("save");
        host.click_text("README.md");
        typed(&mut host, "x");
        assert!(has_text(&host, "●"), "unsaved changes are marked on the tab");
        shortcut(&mut host, "s");
        assert_eq!(std::fs::read_to_string(Path::new(&path).join("README.md")).unwrap(), "x# hi\n");
        assert!(!has_text(&host, "●") && has_text(&host, "×"));
    }

    #[test]
    fn closing_a_dirty_tab_can_save_or_discard() {
        let (mut host, _, path) = app("close");
        host.click_text("README.md");
        typed(&mut host, "x");
        host.click_text("●");
        assert_eq!(host.state().workspace().unwrap().tabs.len(), 1);
        assert!(has_text(&host, "Unsaved changes"));
        host.click_text("Save");
        assert!(host.state().workspace().unwrap().tabs.is_empty(), "save closes the tab");
        assert_eq!(std::fs::read_to_string(Path::new(&path).join("README.md")).unwrap(), "x# hi\n");

        host.state_mut().open_file(Path::new(&path).join("README.md"), false);
        typed(&mut host, "y");
        host.click_text("●");
        host.click_text("Discard");
        assert!(host.state().workspace().unwrap().tabs.is_empty(), "discard closes without saving");
    }

    fn position(host: &TestHost<Madi>, line: &str, col: usize) -> (f32, f32) {
        let t = host.scene().texts().find(|t| t.content == line).expect("the line is on screen");
        let size = host.state().config.font_size();
        let x = Shaper::new().caret_x(line, Editor::text_style(size), col);
        (t.origin.0 + x + 0.5, t.origin.1 + 4.)
    }

    #[test]
    fn the_mouse_places_the_caret_drags_a_selection_and_double_click_picks_a_word() {
        let (mut host, _, _) = app("mouse");
        host.click_text("src");
        host.click_text("main.rs");
        let line = "fn main() {}";
        host.click(position(&host, line, 3));
        assert_eq!(host.state().active_editor().unwrap().doc.cursor(), Pos::new(0, 3));

        host.mouse_down(position(&host, line, 3));
        host.mouse_move(position(&host, line, 7));
        host.mouse_up(position(&host, line, 7));
        assert_eq!(host.state().active_editor().unwrap().doc.selected_text(), "main");

        host.mouse_down_n(position(&host, line, 4), 2);
        host.mouse_up(position(&host, line, 4));
        assert_eq!(host.state().active_editor().unwrap().doc.selected_text(), "main", "double click selects the word");
        typed(&mut host, "X");
        assert_eq!(doc_text(&host), "fn X() {}\n", "typing replaces the selection");
    }

    #[test]
    fn select_all_copy_cut_and_paste_use_the_clipboard() {
        let (mut host, _, _) = app("clip");
        host.click_text("README.md");
        shortcut(&mut host, "a");
        shortcut(&mut host, "c");
        assert_eq!(host.clipboard().as_deref(), Some("# hi\n"));
        shortcut(&mut host, "x");
        assert_eq!(doc_text(&host), "");
        host.set_clipboard("pasted");
        shortcut(&mut host, "v");
        assert_eq!(doc_text(&host), "pasted");
    }

    #[test]
    fn the_caret_is_scrolled_into_view() {
        let (mut host, _, path) = app("reveal");
        let long = (0..200).map(|i| format!("line {i}\n")).collect::<String>();
        let file = Path::new(&path).join("long.txt");
        std::fs::write(&file, long).unwrap();
        host.state_mut().refresh_tree();
        host.frame();
        host.click_text("long.txt");
        assert_eq!(host.scroll_offset(("editor-lines", &file)).1, 0.);
        host.set_modifiers(Modifiers { logo: true, ctrl: true, ..Default::default() });
        press(&mut host, Key::Named(NamedKey::ArrowDown));
        assert!(host.scroll_offset(("editor-lines", &file)).1 > 1000., "jumping to the end scrolls the last line into view");
        assert!(has_text(&host, "line 199"));
    }

    // ---- settings --------------------------------------------------------------------------

    #[test]
    fn settings_open_from_the_shortcut_and_close_without_leaking_input() {
        let (mut host, _, _) = app("settings-shortcut");
        host.click_text("README.md");
        shortcut(&mut host, ",");
        assert!(host.state().settings_open);
        assert!(has_text(&host, "Settings"));

        typed(&mut host, "x");
        assert_eq!(doc_text(&host), "# hi\n", "modal owns keyboard input");

        press(&mut host, Key::Named(NamedKey::Escape));
        assert!(!host.state().settings_open);
        typed(&mut host, "x");
        assert_eq!(doc_text(&host), "x# hi\n", "the editor regains keyboard input");

        host.click((1170., 20.));
        assert!(host.state().settings_open, "the top bar sliders icon opens settings");
    }

    #[test]
    fn settings_close_from_the_header_or_backdrop_but_not_the_modal_body() {
        let (mut host, _, _) = app("settings-dismiss");
        host.state_mut().open_settings();
        host.frame();
        host.click((600., 600.));
        assert!(host.state().settings_open, "a click in the modal does not reach the backdrop");

        host.click_text("×");
        assert!(!host.state().settings_open);
        host.state_mut().open_settings();
        host.frame();
        host.click((10., 100.));
        assert!(!host.state().settings_open, "the backdrop dismisses the modal");
    }

    #[test]
    fn settings_tabs_theme_and_font_size_update_and_persist() {
        let (mut host, root, _) = app("settings-values");
        let config_path = root.join("config.json");
        host.click_text("README.md");
        let light = host.scene().quads().next().unwrap().background;
        host.state_mut().open_settings();
        host.frame();

        host.click_text("Dark");
        assert_eq!(host.state().config.appearance, Appearance::Dark);
        assert_ne!(host.scene().quads().next().unwrap().background, light);
        assert!(std::fs::read_to_string(&config_path).unwrap().contains("\"dark\""));

        host.click_text("Editor");
        assert!(has_text(&host, "Font size") && !has_text(&host, "Theme"));
        host.click_text("+");
        assert_eq!(host.state().config.font_size(), 14.);
        let editor_text = host.scene().texts().find(|t| t.content == "# hi").unwrap();
        assert_eq!(editor_text.style.size, 14., "open editors repaint at the configured size immediately");
        assert!(std::fs::read_to_string(&config_path).unwrap().contains("editor_font_size"));
        for _ in 0..30 {
            host.click_text("+");
        }
        assert_eq!(host.state().config.font_size(), 24.);
        for _ in 0..30 {
            host.click_text("−");
        }
        assert_eq!(host.state().config.font_size(), 10.);
    }

    fn git(dir: &Path, args: &[&str]) {
        let output = std::process::Command::new("git").current_dir(dir).args(args).output().unwrap();
        assert!(output.status.success(), "git {args:?}: {}", String::from_utf8_lossy(&output.stderr));
    }

    #[test]
    fn worktrees_open_a_virtualized_diff_tab() {
        let root = std::env::temp_dir().join("madi-gyeol-test-worktree-diff");
        let _ = std::fs::remove_dir_all(&root);
        let repo = root.join("repo");
        std::fs::create_dir_all(&repo).unwrap();
        git(&repo, &["init", "-q", "-b", "main"]);
        git(&repo, &["config", "user.email", "t@example.test"]);
        git(&repo, &["config", "user.name", "Test"]);
        std::fs::write(repo.join("README.md"), "base\n").unwrap();
        git(&repo, &["add", "."]);
        git(&repo, &["commit", "-qm", "base"]);
        let feature = root.join("feature");
        git(&repo, &["worktree", "add", "-q", "-b", "feature", feature.to_str().unwrap()]);
        let long = "x".repeat(240);
        let content = (0..180).map(|n| format!("line {n:03} {long}\n")).collect::<String>();
        std::fs::write(feature.join("README.md"), content).unwrap();
        git(&feature, &["add", "."]);
        git(&feature, &["commit", "-qm", "feature change"]);

        let config = Config::at(Some(root.join("config.json")));
        let mut host = TestHost::new(Madi::new(Some(repo.to_string_lossy().into_owned()), config), (1000., 700.));
        host.click_text("Worktrees");
        assert!(has_text(&host, "(main)") && has_text(&host, "feature"));
        host.click_text("feature");
        assert!(has_text(&host, "README.md"));
        host.click_text("README.md");
        assert!(host.state().workspace().unwrap().showing_diff);
        assert!(has_text(&host, &("line 000 ".to_owned() + &long)));
        let visible = host.scene().texts().filter(|text| text.content.starts_with("line ")).count();
        assert!(visible < 80, "the diff list should only build rows near the viewport");
    }
}
